
CREATE TABLE IF NOT EXISTS chambers (
id INT NOT NULL AUTO_INCREMENT,
number INT NULL,
PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS doctors (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NULL,
age INT NULL,
PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS patients (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NULL,
age VARCHAR(45) NULL,
chamber_id INT NULL,
doctor_id INT NULL,
PRIMARY KEY (id),
CONSTRAINT chamber_id
FOREIGN KEY (chamber_id)
REFERENCES chambers (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT doctor_id
FOREIGN KEY (doctor_id)
REFERENCES doctors (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS medicaments (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NULL,
PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS patient_medicaments (
patient_id INT NULL,
medicament_id INT NULL,
CONSTRAINT patient_id
FOREIGN KEY (patient_id)
REFERENCES patients (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT medicament_id
FOREIGN KEY (medicament_id)
REFERENCES medicaments (id)
ON DELETE NO ACTION
ON UPDATE NO ACTION);